#!/bin/sh
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/history"
HISTSIZE=10000000
SAVEHIST=10000000
WORDCHARS=${WORDCHARS//\/[&.;]}                                 # Don't consider certain characters part of the word

# Environment variables set everywhere
export EDITOR="nvim"
export BROWSER="brave"
export TERMINAL="konsole"
export PATH="$HOME/.local/bin":$PATH
#export MANPAGER='nvim +Man!'
export MANWIDTH=999
  # Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-R
  # File and Dir colors for ls and other outputs
export LS_OPTIONS='--color=auto'
