#!/bin/sh

function cd_module() {
  emulate -LR bash
	local git_dir="$(git rev-parse --show-toplevel)"

	local module_dir="$(
		git -C "${git_dir}" ls-files -- \
			':!:**/src/**' \
			\
			'*.bnd' \
			'*build.xml' \
			'*pom.xml' |

			#
			# Get the directory name with sed instead of dirname because it is much faster
			#

			sed -E \
				-e 's,[^/]*$,,g' \
				\
				-e 's,/$,,g' \
				-e '/^$/d' |

			#
			# Remove duplicates because some modules have more than one *.bnd file
			#

			uniq |

			#
			# Pass the results to fzf
			#
			fzf \
				--exit-0 \
				--no-multi \
				--query "$*" \
				--select-1 \
			;
	)"

	if [ -n "${module_dir}" ]
	then
		cd "${git_dir}/${module_dir}" || return 1
	fi
}

cleanbundle() {
  emulate -LR bash
  if [[ "$PWD" = */dev/bundles/* ]]; then 
    rm -rf osgi/state/ &&
    rm -rf tomcat-9.0.*/temp/ &&
    rm -rf tomcat-9.0.*/work/ &&
    rm -rf data/* &&
    echo "bundle cleaned"
  else
    echo "not in bundle folder"
  fi
}

#Show Current Branch
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

fFP() {
  emulate -LR bash
	if [ -z "$1" ]
		then
			echo "Please specifcy the branch information: 62 70 71 fix"
			return 0
	elif [ -z "$2" ]
		then
			echo "Please specify the fix-pack/build information"
			return 0
	fi

	if [ "$1" = "62" ]
		then
			git fetch -n upstream tags/fix-pack-base-6210-sp"$2":refs/tags/fix-pack-base-6210-sp"$2"
	elif [ "$1" = "70" ]
		then
			git fetch -n upstream tags/fix-pack-de-"$2"-7010:refs/tags/fix-pack-de-"$2"-7010
	elif [ "$1" = "71" ]
		then
			git fetch -n upstream tags/fix-pack-dxp-"$2"-7110:refs/tags/fix-pack-dxp-"$2"-7110
	elif [ "$1" = "72" ]
		then
			git fetch -n upstream tags/fix-pack-dxp-"$2"-7210:refs/tags/fix-pack-dxp-"$2"-7210
	elif [ "$1" = "73" ]
		then
			git fetch -n upstream tags/fix-pack-dxp-"$2"-7310:refs/tags/fix-pack-dxp-"$2"-7310
	elif [ "$1" = "74" ]
		then
			git fetch -n upstream tags/7.4.13-u"$2":refs/tags/7.4.13-u"$2"
	elif [ "$1" = "mp" ]
		then
			git fetch -n upstream tags/"$2":refs/tags/"$2"
	elif [ "$1" = "fix" ]
		then
			git fetch -n upstream tags/fix-pack-fix-"$2":refs/tags/fix-pack-fix-"$2"
	fi
}

  emulate -LR bash
asci() {
	ant setup-sdk
	ant compile
	ant install-portal-snapshots
}

cdl() {
  cd "$@" && ls -la;
}

branchsync(){
  emulate -LR bash
current_branch=$(git rev-parse --abbrev-ref HEAD)
	git checkout -f "$current_branch"
	git fetch -n upstream
	git merge upstream/"$current_branch"
	git push -f origin "$current_branch"
}

portaltrash() {
  emulate -LR bash
  rm -R .git/gc.log
	rm -R .git/gitk.cache
	git clean -xdf -e '**/*.iml' -e '.gradle/gradle.properties' -e '.idea' -e '.m2' -e "app.server.$USER.properties" -e "build.$USER.properties"
}

cata(){
  emulate -LR bash
	tomcatfile=$(find . -name 'tomcat*' -type d)
	if [[ $tomcatfile == "" ]]; then
		previousdirectory="../"
		for i in {1..5}; do
  			tomcatfile=$(find ${previousdirectory} -name 'tomcat*' -type d)
			if [[ $tomcatfile == "" ]]; then previousdirectory+="../"; else break; fi
		done
	fi
	if [[ $tomcatfile == "" ]]; then echo "ERROR RUNNING COMMAND: check if the command was run inside a bundle"; else ./$tomcatfile/bin/catalina.sh jpda run; fi
}

cdbb(){
  emulate -LR bash
	if [ -f app.server.$USER.properties ]; then
		bundlepath=$(grep -Po '(?<=dir=)[^*]*' app.server.$USER.properties)
		cd $bundlepath
	else
		echo "ERROR RUNNING COMMAND: unable to find the app.server.$USER.properties file" 
	fi
}

createb(){
        if [[ $1 == "" ]]
        then
                name=$(git branch --show-current)
        else
                name=$1
        fi

        if [[ $name == "" ]]
        then
                echo "ERROR WHEN TRYING TO EXECUTE COMMAND: Branch not found or parameter not entered"
        else
                echo "app.server.parent.dir=/home/$USER/dev/bundles/${name}" > app.server.$USER.properties
                cp ~/dev/tags/build.$USER.properties .
                ant setup-profile-dxp
                ant all
                echo "BUNDLE CREATION COMPLETED: Bundle created on path ~/dev/bundles/${name}"
        fi
}

purgenode() {
  emulate -LR bash
  sudo dnf remove nodejs npm -y
  rm -rf /usr/local/lib/node*
  rm -rf /usr/local/include/node*
  rm -rf ~/.npm
}

wipedb() {
  emulate -LR bash
        if [[ $1 == "" ]]
        then
                name=$(lportal)
        else
                name=$1
        fi

        if [[ $name == "" ]]
        then
                echo "ERROR WHEN TRYING TO EXECUTE COMMAND"
        else
                mysql -u root -Bse `drop database ${name}; create database ${name} default character set utf8;`
                echo "${name} database wiped"
        fi
}

# todo function to wipe specifically the db of the bundle in which the user is currently at
wipebundledb() {
  emulate -LR bash

}

# todo function to create a new specified db and then input it into the portal-ext.properties
setupbundledb() {
  emulate -LR bash

}

createdb() {
  emulate -LR bash
        if [[ $1 == "" ]]
        then
                name=$(lportal)
        else
                name=$1
        fi

        if [[ $name == "" ]]
        then
                echo "ERROR WHEN TRYING TO EXECUTE COMMAND"
        else
                mysql -u root -Bse `create database ${name} default character set utf8;`
                echo "${name} database wiped"
        fi
}

everyday(){
  emulate -LR bash
	portalup=$(sudo netstat -tulpn | grep :8000)
	sudo dnf -y update
	if [[ ${portalup} == "" ]]; then 
		cd ~/dev/projects/liferay-portal
    haschanges=0 && [[ $(git status --porcelain | wc -l) -gt 0 ]] && haschanges=1
    isinmaster=0 && [[ $(git rev-parse --abbrev-ref HEAD) == "master" ]] && isinmaster=1

    [[ haschanges -eq 1 ]] && git stash
    [[ isinmaster -eq 0 ]] && git checkout master
    git pull --rebase upstream master
    git push origin master
    [[ isinmaster -eq 0 ]] && git checkout - && git rebase master
    [[ haschanges -eq 1 ]] && git stash pop
		cd -
	else 
		echo "ERRO: Talvez o liferay-portal esteja rodando na sua maquina"; 
	fi
}

function customize_path {
  emulate -LR bash
	export ANT_HOME="/opt/java/ant"
	export ANT_OPTS="-Xmx6144m"

	export GRADLE_OPTS=${ANT_OPTS}

	if [ -z ${JAVA_HOME+x} ]
	then
		export JAVA_HOME="/opt/java/jdk"
	fi

	export NPM_CONFIG_PREFIX=~/.npm-global

	export PATH="${ANT_HOME}/bin:${JAVA_HOME}/bin:${NPM_CONFIG_PREFIX}/bin:/opt/java/maven/bin:~/test:${PATH}"
}

function execute_gradlew {
  emulate -LR bash
	if [ -e ../gradlew ]
	then
		../gradlew ${@}
	elif [ -e ../../gradlew ]
	then
		../../gradlew ${@}
	elif [ -e ../../../gradlew ]
	then
		../../../gradlew ${@}
	elif [ -e ../../../../gradlew ]
	then
		../../../../gradlew ${@}
	elif [ -e ../../../../../gradlew ]
	then
		../../../../../gradlew ${@}
	elif [ -e ../../../../../../gradlew ]
	then
		../../../../../../gradlew ${@}
	elif [ -e ../../../../../../../gradlew ]
	then
		../../../../../../../gradlew ${@}
	elif [ -e ../../../../../../../../gradlew ]
	then
		../../../../../../../../gradlew ${@}
	elif [ -e ../../../../../../../../../gradlew ]
	then
		../../../../../../../../../gradlew ${@}
	else
		echo "Unable to find locate Gradle wrapper."
	fi
}

function git_grep {
  emulate -LR bash
	if [ ${#} -eq 1 ]
	then
		git --no-pager grep --files-with-matches "${1}"
	elif [ ${#} -eq 2 ]
	then
		git --no-pager grep --files-with-matches "${1}" -- "${2}"
	elif [ ${#} -eq 3 ]
	then
		git --no-pager grep --files-with-matches "${1}" -- "${2}" "${3}"
	elif [ ${#} -eq 4 ]
	then
		git --no-pager grep --files-with-matches "${1}" -- "${2}" "${3}" "${4}"
	fi
}

#function gw {
#	execute_gradlew "${@//\//:}" --daemon
#}

gw () {
  emulate -LR bash
	local root_level
	root_level=$(git rev-parse --show-toplevel 2>/dev/null)
	if [[ -n $root_level && -f "$root_level/gradlew" ]]
	then
		root_level="$root_level/gradlew"
	else
		root_level=$(command -v gradle)
	fi
	"$root_level" --console=rich "$@"
}

function parse_git_branch {
  emulate -LR bash
	GIT_DIR_NAME=$(git rev-parse --show-toplevel)

	GIT_DIR_NAME=${GIT_DIR_NAME##*/}

	if [[ "${GIT_DIR_NAME}" =~ -ee-[0-9][^\-]*$ ]]
	then
		echo "ee-${GIT_DIR_NAME##*-ee-}"
	elif [[ "${GIT_DIR_NAME}" =~ -[0-9][^\-]*$ ]]
	then
		echo "${GIT_DIR_NAME##*-}"
	elif [[ "${GIT_DIR_NAME}" =~ com-liferay-osb-asah-private$ ]]
	then
		echo "7.0.x"
	elif [[ "${GIT_DIR_NAME}" =~ -private$ ]]
	then
		echo "${GIT_DIR_NAME}" | sed 's/.*-\([^\-]*\)-private$/\1-private/'
	else
		echo "master"
	fi
}

IJ_CLONE_PATH=/home/me/dev/projects/liferay-intellij

ij() {
  emulate -LR bash
        ${IJ_CLONE_PATH}/intellij_libsources "$@"
}

function parse_git_current_branch {
  emulate -LR bash
	git rev-parse --abbrev-ref HEAD 2>/dev/null
}

function parse_git_current_branch_with_parantheses {
  emulate -LR bash
	parse_git_current_branch | sed 's/.*/(&)/'
}

function switch_to_java_7 {
  emulate -LR bash
	export JAVA_HOME="/opt/java/jdk7"

	export PATH="${JAVA_HOME}/bin:${PATH}"
}

function switch_to_java18 {
  emulate -LR bash
	export JAVA_HOME="/opt/java/jdk18"

	export PATH="${JAVA_HOME}/bin:${PATH}"
}

customize_path
remaps
